// ==========================================
// BASE DE DATOS LOCAL - SIGNIFICADOS DE DUPLAS
// ==========================================
// Formato: "Carta A|Carta B" (EL ORDEN IMPORTA)
// "La Muerte|El Sol" es DISTINTO de "El Sol|La Muerte"
// Si querés ambas combinaciones, cargalas por separado.
//
// Con 78 cartas hay 78 x 77 = 6.006 duplas ordenadas posibles.
// Agregá de a poco las que más uses.
//
// Cuando subas a MongoDB, el servidor ya tiene los endpoints:
//   GET /api/duplas/buscar?a=Carta1&b=Carta2
//   POST /api/admin/duplas (requiere token admin)

window.baseDeDatosDuplas = {
    // Dupla ordenada: Carta de la izquierda | Carta de la derecha
    // ==========================================
// ARCANOS MAYORES X ARCANOS MAYORES (484)
// ==========================================

// --- EL LOCO ---
"El Loco|El Loco": { "<p>next</p>",},
"El Loco|El Mago": { "<p>next</p>",},,
"El Loco|La Sacerdotisa": { "<p>next</p>",},
"El Loco|La Emperatriz": { "<p>next</p>",},
"El Loco|El Emperador": { "<p>next</p>",},
"El Loco|El Papa": { "<p>next</p>",},
"El Loco|Los Enamorados": { "<p>next</p>",},
"El Loco|El Carro": { "<p>next</p>",},
"El Loco|La Justicia": { "<p>next</p>",},
"El Loco|El Ermitaño": { "<p>next</p>",},
"El Loco|La Rueda de la Fortuna":{ "<p>next</p>",},
"El Loco|La Fuerza": { "<p>next</p>",},
"El Loco|El Colgado": { "<p>next</p>",},
"El Loco|La Muerte": { "<p>next</p>",},
"El Loco|La Templanza": { "<p>next</p>",},
"El Loco|El Diablo": { "<p>next</p>",},
"El Loco|La Torre": { "<p>next</p>",},
"El Loco|La Estrella": { "<p>next</p>",},
"El Loco|La Luna": { "<p>next</p>",},
"El Loco|El Sol": { "<p>next</p>",},
"El Loco|El Juicio": { "<p>next</p>",},
"El Loco|El Mundo": { "<p>next</p>",},

// --- EL MAGO ---
"El Mago|El Loco": { "<p>next</p>",},
"El Mago|El Mago": { "<p>next</p>",},
"El Mago|La Sacerdotisa": { "<p>next</p>",},
"El Mago|La Emperatriz": { "<p>next</p>",},
"El Mago|El Emperador": { "<p>next</p>",},
"El Mago|El Papa": { "<p>next</p>",},
"El Mago|Los Enamorados": { "<p>next</p>",},
"El Mago|El Carro": { "<p>next</p>",},
"El Mago|La Justicia": { "<p>next</p>",},
"El Mago|El Ermitaño": { "<p>next</p>",},
"El Mago|La Rueda de la Fortuna": { "<p>next</p>",},
"El Mago|La Fuerza": { "<p>next</p>",},
"El Mago|El Colgado": { "<p>next</p>",},
"El Mago|La Muerte": { "<p>next</p>",},
"El Mago|La Templanza": { "<p>next</p>",},
"El Mago|El Diablo": { "<p>next</p>",},
"El Mago|La Torre": { "<p>next</p>",},
"El Mago|La Estrella": { "<p>next</p>",},
"El Mago|La Luna": { "<p>next</p>",},
"El Mago|El Sol": { "<p>next</p>",},
"El Mago|El Juicio": { "<p>next</p>",},
"El Mago|El Mundo": { "<p>next</p>",},

// --- LA SACERDOTISA ---
"La Sacerdotisa|El Loco": { "<p>next</p>",},
"La Sacerdotisa|El Mago": { "<p>next</p>",},
"La Sacerdotisa|La Sacerdotisa": { "<p>next</p>",},
"La Sacerdotisa|La Emperatriz": { "<p>next</p>",},
"La Sacerdotisa|El Emperador": { "<p>next</p>",},
"La Sacerdotisa|El Papa": { "<p>next</p>",},
"La Sacerdotisa|Los Enamorados": { "<p>next</p>",},
"La Sacerdotisa|El Carro": { "<p>next</p>",},
"La Sacerdotisa|La Justicia": { "<p>next</p>",},
"La Sacerdotisa|El Ermitaño": { "<p>next</p>",},
"La Sacerdotisa|La Rueda de la Fortuna": { "<p>next</p>",},
"La Sacerdotisa|La Fuerza": { "<p>next</p>",},
"La Sacerdotisa|El Colgado": { "<p>next</p>",},
"La Sacerdotisa|La Muerte": { "<p>next</p>",},
"La Sacerdotisa|La Templanza": { "<p>next</p>",},
"La Sacerdotisa|El Diablo": { "<p>next</p>",},
"La Sacerdotisa|La Torre": { "<p>next</p>",},
"La Sacerdotisa|La Estrella": { "<p>next</p>",},
"La Sacerdotisa|La Luna": { "<p>next</p>",},
"La Sacerdotisa|El Sol": { "<p>next</p>",},
"La Sacerdotisa|El Juicio": { "<p>next</p>",},
"La Sacerdotisa|El Mundo": { "<p>next</p>",},

// --- LA EMPERATRIZ ---
"La Emperatriz|El Loco": { "<p>next</p>",},
"La Emperatriz|El Mago": { "<p>next</p>",},
"La Emperatriz|La Sacerdotisa": { "<p>next</p>",},
"La Emperatriz|La Emperatriz": { "<p>next</p>",},
"La Emperatriz|El Emperador": { "<p>next</p>",},
"La Emperatriz|El Papa": { "<p>next</p>",},
"La Emperatriz|Los Enamorados": { "<p>next</p>",},
"La Emperatriz|El Carro": { "<p>next</p>",},
"La Emperatriz|La Justicia": { "<p>next</p>",},
"La Emperatriz|El Ermitaño": { "<p>next</p>",},
"La Emperatriz|La Rueda de la Fortuna": { "<p>next</p>",},
"La Emperatriz|La Fuerza": { "<p>next</p>",},
"La Emperatriz|El Colgado": { "<p>next</p>",},
"La Emperatriz|La Muerte": { "<p>next</p>",},
"La Emperatriz|La Templanza": { "<p>next</p>",},
"La Emperatriz|El Diablo": { "<p>next</p>",},
"La Emperatriz|La Torre": { "<p>next</p>",},
"La Emperatriz|La Estrella": { "<p>next</p>",},
"La Emperatriz|La Luna": { "<p>next</p>",},
"La Emperatriz|El Sol": { "<p>next</p>",},
"La Emperatriz|El Juicio": { "<p>next</p>",},
"La Emperatriz|El Mundo": { "<p>next</p>",},

// --- EL EMPERADOR ---
"El Emperador|El Loco": { "<p>next</p>",},
"El Emperador|El Mago": { "<p>next</p>",},
"El Emperador|La Sacerdotisa": { "<p>next</p>",},
"El Emperador|La Emperatriz": { "<p>next</p>",},
"El Emperador|El Emperador": { "<p>next</p>",},
"El Emperador|El Papa": { "<p>next</p>",},
"El Emperador|Los Enamorados": { "<p>next</p>",},
"El Emperador|El Carro": { "<p>next</p>",},
"El Emperador|La Justicia": { "<p>next</p>",},
"El Emperador|El Ermitaño": { "<p>next</p>",},
"El Emperador|La Rueda de la Fortuna": { "<p>next</p>",},
"El Emperador|La Fuerza": { "<p>next</p>",},
"El Emperador|El Colgado": { "<p>next</p>",},
"El Emperador|La Muerte": { "<p>next</p>",},
"El Emperador|La Templanza": { "<p>next</p>",},
"El Emperador|El Diablo": { "<p>next</p>",},
"El Emperador|La Torre": { "<p>next</p>",},
"El Emperador|La Estrella": { "<p>next</p>",},
"El Emperador|La Luna": { "<p>next</p>",},
"El Emperador|El Sol": { "<p>next</p>",},
"El Emperador|El Juicio": { "<p>next</p>",},
"El Emperador|El Mundo": { "<p>next</p>",},

// --- EL PAPA ---
"El Papa|El Loco": { "<p>next</p>",},
"El Papa|El Mago": { "<p>next</p>",},
"El Papa|La Sacerdotisa": { "<p>next</p>",},
"El Papa|La Emperatriz": { "<p>next</p>",},
"El Papa|El Emperador": { "<p>next</p>",},
"El Papa|El Papa": { "<p>next</p>",},
"El Papa|Los Enamorados": { "<p>next</p>",},
"El Papa|El Carro": { "<p>next</p>",},
"El Papa|La Justicia": { "<p>next</p>",},
"El Papa|El Ermitaño": { "<p>next</p>",},
"El Papa|La Rueda de la Fortuna": { "<p>next</p>",},
"El Papa|La Fuerza": { "<p>next</p>",},
"El Papa|El Colgado": { "<p>next</p>",},
"El Papa|La Muerte": { "<p>next</p>",},
"El Papa|La Templanza": { "<p>next</p>",},
"El Papa|El Diablo": { "<p>next</p>",},
"El Papa|La Torre": { "<p>next</p>",},
"El Papa|La Estrella": { "<p>next</p>",},
"El Papa|La Luna": { "<p>next</p>",},
"El Papa|El Sol": { "<p>next</p>",},
"El Papa|El Juicio": { "<p>next</p>",},
"El Papa|El Mundo": { "<p>next</p>",},

// --- LOS ENAMORADOS ---
"Los Enamorados|El Loco": { "<p>next</p>",},
"Los Enamorados|El Mago": { "<p>next</p>",},
"Los Enamorados|La Sacerdotisa": { "<p>next</p>",},
"Los Enamorados|La Emperatriz": { "<p>next</p>",},
"Los Enamorados|El Emperador": { "<p>next</p>",},
"Los Enamorados|El Papa": { "<p>next</p>",},
"Los Enamorados|Los Enamorados": { "<p>next</p>",},
"Los Enamorados|El Carro": { "<p>next</p>",},
"Los Enamorados|La Justicia": { "<p>next</p>",},
"Los Enamorados|El Ermitaño": { "<p>next</p>",},
"Los Enamorados|La Rueda de la Fortuna": { "<p>next</p>",},
"Los Enamorados|La Fuerza": { "<p>next</p>",},
"Los Enamorados|El Colgado": { "<p>next</p>",},
"Los Enamorados|La Muerte": { "<p>next</p>",},
"Los Enamorados|La Templanza": { "<p>next</p>",},
"Los Enamorados|El Diablo": { "<p>next</p>",},
"Los Enamorados|La Torre": { "<p>next</p>",},
"Los Enamorados|La Estrella": { "<p>next</p>",},
"Los Enamorados|La Luna": { "<p>next</p>",},
"Los Enamorados|El Sol": { "<p>next</p>",},
"Los Enamorados|El Juicio": { "<p>next</p>",},
"Los Enamorados|El Mundo": { "<p>next</p>",},

// --- EL CARRO ---
"El Carro|El Loco": { "<p>next</p>",},
"El Carro|El Mago": { "<p>next</p>",},
"El Carro|La Sacerdotisa": { "<p>next</p>",},
"El Carro|La Emperatriz": { "<p>next</p>",},
"El Carro|El Emperador": { "<p>next</p>",},
"El Carro|El Papa": { "<p>next</p>",},
"El Carro|Los Enamorados": { "<p>next</p>",},
"El Carro|El Carro": { "<p>next</p>",},
"El Carro|La Justicia": { "<p>next</p>",},
"El Carro|El Ermitaño": { "<p>next</p>",},
"El Carro|La Rueda de la Fortuna": { "<p>next</p>",},
"El Carro|La Fuerza": { "<p>next</p>",},
"El Carro|El Colgado": { "<p>next</p>",},
"El Carro|La Muerte": { "<p>next</p>",},
"El Carro|La Templanza": { "<p>next</p>",},
"El Carro|El Diablo": { "<p>next</p>",},
"El Carro|La Torre": { "<p>next</p>",},
"El Carro|La Estrella": { "<p>next</p>",},
"El Carro|La Luna": { "<p>next</p>",},
"El Carro|El Sol": { "<p>next</p>",},
"El Carro|El Juicio": { "<p>next</p>",},
"El Carro|El Mundo": { "<p>next</p>",},

// --- LA JUSTICIA ---
"La Justicia|El Loco": { "<p>next</p>",},
"La Justicia|El Mago": { "<p>next</p>",},
"La Justicia|La Sacerdotisa": { "<p>next</p>",},
"La Justicia|La Emperatriz": { "<p>next</p>",},
"La Justicia|El Emperador": { "<p>next</p>",},
"La Justicia|El Papa": { "<p>next</p>",},
"La Justicia|Los Enamorados": { "<p>next</p>",},
"La Justicia|El Carro": { "<p>next</p>",},
"La Justicia|La Justicia": { "<p>next</p>",},
"La Justicia|El Ermitaño": { "<p>next</p>",},
"La Justicia|La Rueda de la Fortuna": { "<p>next</p>",},
"La Justicia|La Fuerza": { "<p>next</p>",},
"La Justicia|El Colgado": { "<p>next</p>",},
"La Justicia|La Muerte": { "<p>next</p>",},
"La Justicia|La Templanza": { "<p>next</p>",},
"La Justicia|El Diablo": { "<p>next</p>",},
"La Justicia|La Torre": { "<p>next</p>",},
"La Justicia|La Estrella": { "<p>next</p>",},
"La Justicia|La Luna": { "<p>next</p>",},
"La Justicia|El Sol": { "<p>next</p>",},
"La Justicia|El Juicio": { "<p>next</p>",},
"La Justicia|El Mundo": { "<p>next</p>",},

// --- EL ERMITAÑO ---
"El Ermitaño|El Loco": { "<p>next</p>",},
"El Ermitaño|El Mago": { "<p>next</p>",},
"El Ermitaño|La Sacerdotisa": { "<p>next</p>",},
"El Ermitaño|La Emperatriz": { "<p>next</p>",},
"El Ermitaño|El Emperador": { "<p>next</p>",},
"El Ermitaño|El Papa": { "<p>next</p>",},
"El Ermitaño|Los Enamorados": { "<p>next</p>",},
"El Ermitaño|El Carro": { "<p>next</p>",},
"El Ermitaño|La Justicia": { "<p>next</p>",},
"El Ermitaño|El Ermitaño": { "<p>next</p>",},
"El Ermitaño|La Rueda de la Fortuna": { "<p>next</p>",},
"El Ermitaño|La Fuerza": { "<p>next</p>",},
"El Ermitaño|El Colgado": { "<p>next</p>",},
"El Ermitaño|La Muerte": { "<p>next</p>",},
"El Ermitaño|La Templanza": { "<p>next</p>",},
"El Ermitaño|El Diablo": { "<p>next</p>",},
"El Ermitaño|La Torre": { "<p>next</p>",},
"El Ermitaño|La Estrella": { "<p>next</p>",},
"El Ermitaño|La Luna": { "<p>next</p>",},
"El Ermitaño|El Sol": { "<p>next</p>",},
"El Ermitaño|El Juicio": { "<p>next</p>",},
"El Ermitaño|El Mundo": { "<p>next</p>",},

// --- LA RUEDA DE LA FORTUNA ---
"La Rueda de la Fortuna|El Loco": { "<p>next</p>",},
"La Rueda de la Fortuna|El Mago": { "<p>next</p>",},
"La Rueda de la Fortuna|La Sacerdotisa": { "<p>next</p>",},
"La Rueda de la Fortuna|La Emperatriz": { "<p>next</p>",},
"La Rueda de la Fortuna|El Emperador": { "<p>next</p>",},
"La Rueda de la Fortuna|El Papa": { "<p>next</p>",},
"La Rueda de la Fortuna|Los Enamorados": { "<p>next</p>",},
"La Rueda de la Fortuna|El Carro": { "<p>next</p>",},
"La Rueda de la Fortuna|La Justicia": { "<p>next</p>",},
"La Rueda de la Fortuna|El Ermitaño": { "<p>next</p>",},
"La Rueda de la Fortuna|La Rueda de la Fortuna": { "<p>next</p>",},
"La Rueda de la Fortuna|La Fuerza": { "<p>next</p>",},
"La Rueda de la Fortuna|El Colgado": { "<p>next</p>",},
"La Rueda de la Fortuna|La Muerte": { "<p>next</p>",},
"La Rueda de la Fortuna|La Templanza": { "<p>next</p>",},
"La Rueda de la Fortuna|El Diablo": { "<p>next</p>",},
"La Rueda de la Fortuna|La Torre": { "<p>next</p>",},
"La Rueda de la Fortuna|La Estrella": { "<p>next</p>",},
"La Rueda de la Fortuna|La Luna": { "<p>next</p>",},
"La Rueda de la Fortuna|El Sol": { "<p>next</p>",},
"La Rueda de la Fortuna|El Juicio": { "<p>next</p>",},
"La Rueda de la Fortuna|El Mundo": { "<p>next</p>",},

// --- LA FUERZA ---
"La Fuerza|El Loco": { "<p>next</p>",},
"La Fuerza|El Mago": { "<p>next</p>",},
"La Fuerza|La Sacerdotisa": { "<p>next</p>",},
"La Fuerza|La Emperatriz": { "<p>next</p>",},
"La Fuerza|El Emperador": { "<p>next</p>",},
"La Fuerza|El Papa": { "<p>next</p>",},
"La Fuerza|Los Enamorados": { "<p>next</p>",},
"La Fuerza|El Carro": { "<p>next</p>",},
"La Fuerza|La Justicia": { "<p>next</p>",},
"La Fuerza|El Ermitaño": { "<p>next</p>",},
"La Fuerza|La Rueda de la Fortuna": { "<p>next</p>",},
"La Fuerza|La Fuerza": { "<p>next</p>",},
"La Fuerza|El Colgado": { "<p>next</p>",},
"La Fuerza|La Muerte": { "<p>next</p>",},
"La Fuerza|La Templanza": { "<p>next</p>",},
"La Fuerza|El Diablo": { "<p>next</p>",},
"La Fuerza|La Torre": { "<p>next</p>",},
"La Fuerza|La Estrella": { "<p>next</p>",},
"La Fuerza|La Luna": { "<p>next</p>",},
"La Fuerza|El Sol": { "<p>next</p>",},
"La Fuerza|El Juicio": { "<p>next</p>",},
"La Fuerza|El Mundo": { "<p>next</p>",},

// --- EL COLGADO ---
"El Colgado|El Loco": { "<p>next</p>",},
"El Colgado|El Mago": { "<p>next</p>",},
"El Colgado|La Sacerdotisa": { "<p>next</p>",},
"El Colgado|La Emperatriz": { "<p>next</p>",},
"El Colgado|El Emperador": { "<p>next</p>",},
"El Colgado|El Papa": { "<p>next</p>",},
"El Colgado|Los Enamorados": { "<p>next</p>",},
"El Colgado|El Carro": { "<p>next</p>",},
"El Colgado|La Justicia": { "<p>next</p>",},
"El Colgado|El Ermitaño": { "<p>next</p>",},
"El Colgado|La Rueda de la Fortuna": { "<p>next</p>",},
"El Colgado|La Fuerza": { "<p>next</p>",},
"El Colgado|El Colgado": { "<p>next</p>",},
"El Colgado|La Muerte": { "<p>next</p>",},
"El Colgado|La Templanza": { "<p>next</p>",},
"El Colgado|El Diablo": { "<p>next</p>",},
"El Colgado|La Torre": { "<p>next</p>",},
"El Colgado|La Estrella": { "<p>next</p>",},
"El Colgado|La Luna": { "<p>next</p>",},
"El Colgado|El Sol": { "<p>next</p>",},
"El Colgado|El Juicio": { "<p>next</p>",},
"El Colgado|El Mundo": { "<p>next</p>",},

// --- LA MUERTE ---
"La Muerte|El Loco": { "<p>next</p>",},
"La Muerte|El Mago": { "<p>next</p>",},
"La Muerte|La Sacerdotisa": { "<p>next</p>",},
"La Muerte|La Emperatriz": { "<p>next</p>",},
"La Muerte|El Emperador": { "<p>next</p>",},
"La Muerte|El Papa": { "<p>next</p>",},
"La Muerte|Los Enamorados": { "<p>next</p>",},
"La Muerte|El Carro": { "<p>next</p>",},
"La Muerte|La Justicia": { "<p>next</p>",},
"La Muerte|El Ermitaño": { "<p>next</p>",},
"La Muerte|La Rueda de la Fortuna": { "<p>next</p>",},
"La Muerte|La Fuerza": { "<p>next</p>",},
"La Muerte|El Colgado": { "<p>next</p>",},
"La Muerte|La Muerte": { "<p>next</p>",},
"La Muerte|La Templanza": { "<p>next</p>",},
"La Muerte|El Diablo": { "<p>next</p>",},
"La Muerte|La Torre": { "<p>next</p>",},
"La Muerte|La Estrella": { "<p>next</p>",},
"La Muerte|La Luna": { "<p>next</p>",},
"La Muerte|El Sol": { "<p>next</p>",},
"La Muerte|El Juicio": { "<p>next</p>",},
"La Muerte|El Mundo": { "<p>next</p>",},

// --- LA TEMPLANZA ---
"La Templanza|El Loco": { "<p>next</p>",},
"La Templanza|El Mago": { "<p>next</p>",},
"La Templanza|La Sacerdotisa": { "<p>next</p>",},
"La Templanza|La Emperatriz": { "<p>next</p>",},
"La Templanza|El Emperador": { "<p>next</p>",},
"La Templanza|El Papa": { "<p>next</p>",},
"La Templanza|Los Enamorados": { "<p>next</p>",},
"La Templanza|El Carro": { "<p>next</p>",},
"La Templanza|La Justicia": { "<p>next</p>",},
"La Templanza|El Ermitaño": { "<p>next</p>",},
"La Templanza|La Rueda de la Fortuna": { "<p>next</p>",},
"La Templanza|La Fuerza": { "<p>next</p>",},
"La Templanza|El Colgado": { "<p>next</p>",},
"La Templanza|La Muerte": { "<p>next</p>",},
"La Templanza|La Templanza": { "<p>next</p>",},
"La Templanza|El Diablo": { "<p>next</p>",},
"La Templanza|La Torre": { "<p>next</p>",},
"La Templanza|La Estrella": { "<p>next</p>",},
"La Templanza|La Luna": { "<p>next</p>",},
"La Templanza|El Sol": { "<p>next</p>",},
"La Templanza|El Juicio": { "<p>next</p>",},
"La Templanza|El Mundo": { "<p>next</p>",},

// --- EL DIABLO ---
"El Diablo|El Loco": { "<p>next</p>",},
"El Diablo|El Mago": { "<p>next</p>",},
"El Diablo|La Sacerdotisa": { "<p>next</p>",},
"El Diablo|La Emperatriz": { "<p>next</p>",},
"El Diablo|El Emperador": { "<p>next</p>",},
"El Diablo|El Papa": { "<p>next</p>",},
"El Diablo|Los Enamorados": { "<p>next</p>",},
"El Diablo|El Carro": { "<p>next</p>",},
"El Diablo|La Justicia": { "<p>next</p>",},
"El Diablo|El Ermitaño": { "<p>next</p>",},
"El Diablo|La Rueda de la Fortuna": { "<p>next</p>",},
"El Diablo|La Fuerza": { "<p>next</p>",},
"El Diablo|El Colgado": { "<p>next</p>",},
"El Diablo|La Muerte": { "<p>next</p>",},
"El Diablo|La Templanza": { "<p>next</p>",},
"El Diablo|El Diablo": { "<p>next</p>",},
"El Diablo|La Torre": { "<p>next</p>",},
"El Diablo|La Estrella": { "<p>next</p>",},
"El Diablo|La Luna": { "<p>next</p>",},
"El Diablo|El Sol": { "<p>next</p>",},
"El Diablo|El Juicio": { "<p>next</p>",},
"El Diablo|El Mundo": { "<p>next</p>",},

// --- LA TORRE ---
"La Torre|El Loco": { "<p>next</p>",},
"La Torre|El Mago": { "<p>next</p>",},
"La Torre|La Sacerdotisa": { "<p>next</p>",},
"La Torre|La Emperatriz": { "<p>next</p>",},
"La Torre|El Emperador": { "<p>next</p>",},
"La Torre|El Papa": { "<p>next</p>",},
"La Torre|Los Enamorados": { "<p>next</p>",},
"La Torre|El Carro": { "<p>next</p>",},
"La Torre|La Justicia": { "<p>next</p>",},
"La Torre|El Ermitaño": { "<p>next</p>",},
"La Torre|La Rueda de la Fortuna": { "<p>next</p>",},
"La Torre|La Fuerza": { "<p>next</p>",},
"La Torre|El Colgado": { "<p>next</p>",},
"La Torre|La Muerte": { "<p>next</p>",},
"La Torre|La Templanza": { "<p>next</p>",},
"La Torre|El Diablo": { "<p>next</p>",},
"La Torre|La Torre": { "<p>next</p>",},
"La Torre|La Estrella": { "<p>next</p>",},
"La Torre|La Luna": { "<p>next</p>",},
"La Torre|El Sol": { "<p>next</p>",},
"La Torre|El Juicio": { "<p>next</p>",},
"La Torre|El Mundo": { "<p>next</p>",},
// --- LA ESTRELLA ---
"La Estrella|El Loco": { "<p>next</p>",},
"La Estrella|El Mago": { "<p>next</p>",},
"La Estrella|La Sacerdotisa": { "<p>next</p>",},
"La Estrella|La Emperatriz": { "<p>next</p>",},
"La Estrella|El Emperador": { "<p>next</p>",},
"La Estrella|El Papa": { "<p>next</p>",},
"La Estrella|Los Enamorados": { "<p>next</p>",},
"La Estrella|El Carro": { "<p>next</p>",},
"La Estrella|La Justicia": { "<p>next</p>",},
"La Estrella|El Ermitaño": { "<p>next</p>",},
"La Estrella|La Rueda de la Fortuna": { "<p>next</p>",},
"La Estrella|La Fuerza": { "<p>next</p>",},
"La Estrella|El Colgado": { "<p>next</p>",},
"La Estrella|La Muerte": { "<p>next</p>",},
"La Estrella|La Templanza": { "<p>next</p>",},
"La Estrella|El Diablo": { "<p>next</p>",},
"La Estrella|La Torre": { "<p>next</p>",},
"La Estrella|La Estrella": { "<p>next</p>",},
"La Estrella|La Luna": { "<p>next</p>",},
"La Estrella|El Sol": { "<p>next</p>",},
"La Estrella|El Juicio": { "<p>next</p>",},
"La Estrella|El Mundo": { "<p>next</p>",},

// --- LA LUNA ---
"La Luna|El Loco": { "<p>next</p>",},
"La Luna|El Mago": { "<p>next</p>",},
"La Luna|La Sacerdotisa": { "<p>next</p>",},
"La Luna|La Emperatriz": { "<p>next</p>",},
"La Luna|El Emperador": { "<p>next</p>",},
"La Luna|El Papa": { "<p>next</p>",},
"La Luna|Los Enamorados": { "<p>next</p>",},
"La Luna|El Carro": { "<p>next</p>",},
"La Luna|La Justicia": { "<p>next</p>",},
"La Luna|El Ermitaño": { "<p>next</p>",},
"La Luna|La Rueda de la Fortuna": { "<p>next</p>",},
"La Luna|La Fuerza": { "<p>next</p>",},
"La Luna|El Colgado": { "<p>next</p>",},
"La Luna|La Muerte": { "<p>next</p>",},
"La Luna|La Templanza": { "<p>next</p>",},
"La Luna|El Diablo": { "<p>next</p>",},
"La Luna|La Torre": { "<p>next</p>",},
"La Luna|La Estrella": { "<p>next</p>",},
"La Luna|La Luna": { "<p>next</p>",},
"La Luna|El Sol": { "<p>next</p>",},
"La Luna|El Juicio": { "<p>next</p>",},
"La Luna|El Mundo": { "<p>next</p>",},

// --- EL SOL ---
"El Sol|El Loco": { "<p>next</p>",},
"El Sol|El Mago": { "<p>next</p>",},
"El Sol|La Sacerdotisa": { "<p>next</p>",},
"El Sol|La Emperatriz": { "<p>next</p>",},
"El Sol|El Emperador": { "<p>next</p>",},
"El Sol|El Papa": { "<p>next</p>",},
"El Sol|Los Enamorados": { "<p>next</p>",},
"El Sol|El Carro": { "<p>next</p>",},
"El Sol|La Justicia": { "<p>next</p>",},
"El Sol|El Ermitaño": { "<p>next</p>",},
"El Sol|La Rueda de la Fortuna": { "<p>next</p>",},
"El Sol|La Fuerza": { "<p>next</p>",},
"El Sol|El Colgado": { "<p>next</p>",},
"El Sol|La Muerte": { "<p>next</p>",},
"El Sol|La Templanza": { "<p>next</p>",},
"El Sol|El Diablo": { "<p>next</p>",},
"El Sol|La Torre": { "<p>next</p>",},
"El Sol|La Estrella": { "<p>next</p>",},
"El Sol|La Luna": { "<p>next</p>",},
"El Sol|El Sol": { "<p>next</p>",},
"El Sol|El Juicio": { "<p>next</p>",},
"El Sol|El Mundo": { "<p>next</p>",},

// --- EL JUICIO ---
"El Juicio|El Loco": { "<p>next</p>",},
"El Juicio|El Mago": { "<p>next</p>",},
"El Juicio|La Sacerdotisa": { "<p>next</p>",},
"El Juicio|La Emperatriz": { "<p>next</p>",},
"El Juicio|El Emperador": { "<p>next</p>",},
"El Juicio|El Papa": { "<p>next</p>",},
"El Juicio|Los Enamorados": { "<p>next</p>",},
"El Juicio|El Carro": { "<p>next</p>",},
"El Juicio|La Justicia": { "<p>next</p>",},
"El Juicio|El Ermitaño": { "<p>next</p>",},
"El Juicio|La Rueda de la Fortuna": { "<p>next</p>",},
"El Juicio|La Fuerza": { "<p>next</p>",},
"El Juicio|El Colgado": { "<p>next</p>",},
"El Juicio|La Muerte": { "<p>next</p>",},
"El Juicio|La Templanza": { "<p>next</p>",},
"El Juicio|El Diablo": { "<p>next</p>",},
"El Juicio|La Torre": { "<p>next</p>",},
"El Juicio|La Estrella": { "<p>next</p>",},
"El Juicio|La Luna": { "<p>next</p>",},
"El Juicio|El Sol": { "<p>next</p>",},
"El Juicio|El Juicio": { "<p>next</p>",},
"El Juicio|El Mundo": { "<p>next</p>",},

// --- EL MUNDO ---
"El Mundo|El Loco": { "<p>next</p>",},
"El Mundo|El Mago": { "<p>next</p>",},
"El Mundo|La Sacerdotisa": { "<p>next</p>",},
"El Mundo|La Emperatriz": { "<p>next</p>",},
"El Mundo|El Emperador": { "<p>next</p>",},
"El Mundo|El Papa": { "<p>next</p>",},
"El Mundo|Los Enamorados": { "<p>next</p>",},
"El Mundo|El Carro": { "<p>next</p>",},
"El Mundo|La Justicia": { "<p>next</p>",},
"El Mundo|El Ermitaño": { "<p>next</p>",},
"El Mundo|La Rueda de la Fortuna": { "<p>next</p>",},
"El Mundo|La Fuerza": { "<p>next</p>",},
"El Mundo|El Colgado": { "<p>next</p>",},
"El Mundo|La Muerte": { "<p>next</p>",},
"El Mundo|La Templanza": { "<p>next</p>",},
"El Mundo|El Diablo": { "<p>next</p>",},
"El Mundo|La Torre": { "<p>next</p>",},
"El Mundo|La Estrella": { "<p>next</p>",},
"El Mundo|La Luna": { "<p>next</p>",},
"El Mundo|El Sol": { "<p>next</p>",},
"El Mundo|El Juicio": { "<p>next</p>",},
"El Mundo|El Mundo": { "<p>next</p>",},

// ==========================================
// ARCANOS MAYORES X ARCANOS MENORES (COPAS) (308)
// ==========================================
"El Loco|As de Copas": { "<p>next</p>",},
"El Loco|2 de Copas": { "<p>next</p>",},
"El Loco|3 de Copas": { "<p>next</p>",},
"El Loco|4 de Copas": { "<p>next</p>",},
"El Loco|5 de Copas": { "<p>next</p>",},
"El Loco|6 de Copas": { "<p>next</p>",},
"El Loco|7 de Copas": { "<p>next</p>",},
"El Loco|8 de Copas": { "<p>next</p>",},
"El Loco|9 de Copas": { "<p>next</p>",},
"El Loco|10 de Copas": { "<p>next</p>",},
"El Loco|Sota de Copas": { "<p>next</p>",},
"El Loco|Caballo de Copas": { "<p>next</p>",},
"El Loco|Reina de Copas": { "<p>next</p>",},
"El Loco|Rey de Copas": { "<p>next</p>",},

"El Mago|As de Copas": { "<p>next</p>",},
"El Mago|2 de Copas": { "<p>next</p>",},
"El Mago|3 de Copas": { "<p>next</p>",},
"El Mago|4 de Copas": { "<p>next</p>",},
"El Mago|5 de Copas": { "<p>next</p>",},
"El Mago|6 de Copas": { "<p>next</p>",},
"El Mago|7 de Copas": { "<p>next</p>",},
"El Mago|8 de Copas": { "<p>next</p>",},
"El Mago|9 de Copas": { "<p>next</p>",},
"El Mago|10 de Copas": { "<p>next</p>",},
"El Mago|Sota de Copas": { "<p>next</p>",},
"El Mago|Caballo de Copas": { "<p>next</p>",},
"El Mago|Reina de Copas": { "<p>next</p>",},
"El Mago|Rey de Copas": { "<p>next</p>",},

"La Sacerdotisa|As de Copas": { "<p>next</p>",},
"La Sacerdotisa|2 de Copas": { "<p>next</p>",},
"La Sacerdotisa|3 de Copas": { "<p>next</p>",},
"La Sacerdotisa|4 de Copas": { "<p>next</p>",},
"La Sacerdotisa|5 de Copas": { "<p>next</p>",},
"La Sacerdotisa|6 de Copas": { "<p>next</p>",},
"La Sacerdotisa|7 de Copas": { "<p>next</p>",},
"La Sacerdotisa|8 de Copas": { "<p>next</p>",},
"La Sacerdotisa|9 de Copas": { "<p>next</p>",},
"La Sacerdotisa|10 de Copas": { "<p>next</p>",},
"La Sacerdotisa|Sota de Copas": { "<p>next</p>",},
"La Sacerdotisa|Caballo de Copas": { "<p>next</p>",},
"La Sacerdotisa|Reina de Copas": { "<p>next</p>",},
"La Sacerdotisa|Rey de Copas": { "<p>next</p>",},

"La Emperatriz|As de Copas": { "<p>next</p>",},
"La Emperatriz|2 de Copas": { "<p>next</p>",},
"La Emperatriz|3 de Copas": { "<p>next</p>",},
"La Emperatriz|4 de Copas": { "<p>next</p>",},
"La Emperatriz|5 de Copas": { "<p>next</p>",},
"La Emperatriz|6 de Copas": { "<p>next</p>",},
"La Emperatriz|7 de Copas": { "<p>next</p>",},
"La Emperatriz|8 de Copas": { "<p>next</p>",},
"La Emperatriz|9 de Copas": { "<p>next</p>",},
"La Emperatriz|10 de Copas": { "<p>next</p>",},
"La Emperatriz|Sota de Copas": { "<p>next</p>",},
"La Emperatriz|Caballo de Copas": { "<p>next</p>",},
"La Emperatriz|Reina de Copas": { "<p>next</p>",},
"La Emperatriz|Rey de Copas": { "<p>next</p>",},

"El Emperador|As de Copas": { "<p>next</p>",},
"El Emperador|2 de Copas": { "<p>next</p>",},
"El Emperador|3 de Copas": { "<p>next</p>",},
"El Emperador|4 de Copas": { "<p>next</p>",},
"El Emperador|5 de Copas": { "<p>next</p>",},
"El Emperador|6 de Copas": { "<p>next</p>",},
"El Emperador|7 de Copas": { "<p>next</p>",},
"El Emperador|8 de Copas": { "<p>next</p>",},
"El Emperador|9 de Copas": { "<p>next</p>",},
"El Emperador|10 de Copas": { "<p>next</p>",},
"El Emperador|Sota de Copas": { "<p>next</p>",},
"El Emperador|Caballo de Copas": { "<p>next</p>",},
"El Emperador|Reina de Copas": { "<p>next</p>",},
"El Emperador|Rey de Copas": { "<p>next</p>",},

"El Papa|As de Copas": { "<p>next</p>",},
"El Papa|2 de Copas": { "<p>next</p>",},
"El Papa|3 de Copas": { "<p>next</p>",},
"El Papa|4 de Copas": { "<p>next</p>",},
"El Papa|5 de Copas": { "<p>next</p>",},
"El Papa|6 de Copas": { "<p>next</p>",},
"El Papa|7 de Copas": { "<p>next</p>",},
"El Papa|8 de Copas": { "<p>next</p>",},
"El Papa|9 de Copas": { "<p>next</p>",},
"El Papa|10 de Copas": { "<p>next</p>",},
"El Papa|Sota de Copas": { "<p>next</p>",},
"El Papa|Caballo de Copas": { "<p>next</p>",},
"El Papa|Reina de Copas": { "<p>next</p>",},
"El Papa|Rey de Copas": { "<p>next</p>",},

"Los Enamorados|As de Copas": { "<p>next</p>",},
"Los Enamorados|2 de Copas": { "<p>next</p>",},
"Los Enamorados|3 de Copas": { "<p>next</p>",},
"Los Enamorados|4 de Copas": { "<p>next</p>",},
"Los Enamorados|5 de Copas": { "<p>next</p>",},
"Los Enamorados|6 de Copas": { "<p>next</p>",},
"Los Enamorados|7 de Copas": { "<p>next</p>",},
"Los Enamorados|8 de Copas": { "<p>next</p>",},
"Los Enamorados|9 de Copas": { "<p>next</p>",},
"Los Enamorados|10 de Copas": { "<p>next</p>",},
"Los Enamorados|Sota de Copas": { "<p>next</p>",},
"Los Enamorados|Caballo de Copas": { "<p>next</p>",},
"Los Enamorados|Reina de Copas": { "<p>next</p>",},
"Los Enamorados|Rey de Copas": { "<p>next</p>",},

"El Carro|As de Copas": { "<p>next</p>",},
"El Carro|2 de Copas": { "<p>next</p>",},
"El Carro|3 de Copas": { "<p>next</p>",},
"El Carro|4 de Copas": { "<p>next</p>",},
"El Carro|5 de Copas": { "<p>next</p>",},
"El Carro|6 de Copas": { "<p>next</p>",},
"El Carro|7 de Copas": { "<p>next</p>",},
"El Carro|8 de Copas": { "<p>next</p>",},
"El Carro|9 de Copas": { "<p>next</p>",},
"El Carro|10 de Copas": { "<p>next</p>",},
"El Carro|Sota de Copas": { "<p>next</p>",},
"El Carro|Caballo de Copas": { "<p>next</p>",},
"El Carro|Reina de Copas": { "<p>next</p>",},
"El Carro|Rey de Copas": { "<p>next</p>",},

"La Justicia|As de Copas": { "<p>next</p>",},
"La Justicia|2 de Copas": { "<p>next</p>",},
"La Justicia|3 de Copas": { "<p>next</p>",},
"La Justicia|4 de Copas": { "<p>next</p>",},
"La Justicia|5 de Copas": { "<p>next</p>",},
"La Justicia|6 de Copas": { "<p>next</p>",},
"La Justicia|7 de Copas": { "<p>next</p>",},
"La Justicia|8 de Copas": { "<p>next</p>",},
"La Justicia|9 de Copas": { "<p>next</p>",},
"La Justicia|10 de Copas": { "<p>next</p>",},
"La Justicia|Sota de Copas": { "<p>next</p>",},
"La Justicia|Caballo de Copas": { "<p>next</p>",},
"La Justicia|Reina de Copas": { "<p>next</p>",},
"La Justicia|Rey de Copas": { "<p>next</p>",},

"El Ermitaño|As de Copas": { "<p>next</p>",},
"El Ermitaño|2 de Copas": { "<p>next</p>",},
"El Ermitaño|3 de Copas": { "<p>next</p>",},
"El Ermitaño|4 de Copas": { "<p>next</p>",},
"El Ermitaño|5 de Copas": { "<p>next</p>",},
"El Ermitaño|6 de Copas": { "<p>next</p>",},
"El Ermitaño|7 de Copas": { "<p>next</p>",},
"El Ermitaño|8 de Copas": { "<p>next</p>",},
"El Ermitaño|9 de Copas": { "<p>next</p>",},
"El Ermitaño|10 de Copas": { "<p>next</p>",},
"El Ermitaño|Sota de Copas": { "<p>next</p>",},
"El Ermitaño|Caballo de Copas": { "<p>next</p>",},
"El Ermitaño|Reina de Copas": { "<p>next</p>",},
"El Ermitaño|Rey de Copas": { "<p>next</p>",},

"La Rueda de la Fortuna|As de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|2 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|3 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|4 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|5 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|6 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|7 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|8 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|9 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|10 de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|Sota de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|Caballo de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|Reina de Copas": { "<p>next</p>",},
"La Rueda de la Fortuna|Rey de Copas": { "<p>next</p>",},

"La Fuerza|As de Copas": { "<p>next</p>",},
"La Fuerza|2 de Copas": { "<p>next</p>",},
"La Fuerza|3 de Copas": { "<p>next</p>",},
"La Fuerza|4 de Copas": { "<p>next</p>",},
"La Fuerza|5 de Copas": { "<p>next</p>",},
"La Fuerza|6 de Copas": { "<p>next</p>",},
"La Fuerza|7 de Copas": { "<p>next</p>",},
"La Fuerza|8 de Copas": { "<p>next</p>",},
"La Fuerza|9 de Copas": { "<p>next</p>",},
"La Fuerza|10 de Copas": { "<p>next</p>",},
"La Fuerza|Sota de Copas": { "<p>next</p>",},
"La Fuerza|Caballo de Copas": { "<p>next</p>",},
"La Fuerza|Reina de Copas": { "<p>next</p>",},
"La Fuerza|Rey de Copas": { "<p>next</p>",},

"El Colgado|As de Copas": { "<p>next</p>",},
"El Colgado|2 de Copas": { "<p>next</p>",},
"El Colgado|3 de Copas": { "<p>next</p>",},
"El Colgado|4 de Copas": { "<p>next</p>",},
"El Colgado|5 de Copas": { "<p>next</p>",},
"El Colgado|6 de Copas": { "<p>next</p>",},
"El Colgado|7 de Copas": { "<p>next</p>",},
"El Colgado|8 de Copas": { "<p>next</p>",},
"El Colgado|9 de Copas": { "<p>next</p>",},
"El Colgado|10 de Copas": { "<p>next</p>",},
"El Colgado|Sota de Copas": { "<p>next</p>",},
"El Colgado|Caballo de Copas": { "<p>next</p>",},
"El Colgado|Reina de Copas": { "<p>next</p>",},
"El Colgado|Rey de Copas": { "<p>next</p>",},

"La Muerte|As de Copas": { "<p>next</p>",},
"La Muerte|2 de Copas": { "<p>next</p>",},
"La Muerte|3 de Copas": { "<p>next</p>",},
"La Muerte|4 de Copas": { "<p>next</p>",},
"La Muerte|5 de Copas": { "<p>next</p>",},
"La Muerte|6 de Copas": { "<p>next</p>",},
"La Muerte|7 de Copas": { "<p>next</p>",},
"La Muerte|8 de Copas": { "<p>next</p>",},
"La Muerte|9 de Copas": { "<p>next</p>",},
"La Muerte|10 de Copas": { "<p>next</p>",},
"La Muerte|Sota de Copas": { "<p>next</p>",},
"La Muerte|Caballo de Copas": { "<p>next</p>",},
"La Muerte|Reina de Copas": { "<p>next</p>",},
"La Muerte|Rey de Copas": { "<p>next</p>",},

"La Templanza|As de Copas": { "<p>next</p>",},
"La Templanza|2 de Copas": { "<p>next</p>",},
"La Templanza|3 de Copas": { "<p>next</p>",},
"La Templanza|4 de Copas": { "<p>next</p>",},
"La Templanza|5 de Copas": { "<p>next</p>",},
"La Templanza|6 de Copas": { "<p>next</p>",},
"La Templanza|7 de Copas": { "<p>next</p>",},
"La Templanza|8 de Copas": { "<p>next</p>",},
"La Templanza|9 de Copas": { "<p>next</p>",},
"La Templanza|10 de Copas": { "<p>next</p>",},
"La Templanza|Sota de Copas": { "<p>next</p>",},
"La Templanza|Caballo de Copas": { "<p>next</p>",},
"La Templanza|Reina de Copas": { "<p>next</p>",},
"La Templanza|Rey de Copas": { "<p>next</p>",},

"El Diablo|As de Copas": { "<p>next</p>",},
"El Diablo|2 de Copas": { "<p>next</p>",},
"El Diablo|3 de Copas": { "<p>next</p>",},
"El Diablo|4 de Copas": { "<p>next</p>",},
"El Diablo|5 de Copas": { "<p>next</p>",},
"El Diablo|6 de Copas": { "<p>next</p>",},
"El Diablo|7 de Copas": { "<p>next</p>",},
"El Diablo|8 de Copas": { "<p>next</p>",},
"El Diablo|9 de Copas": { "<p>next</p>",},
"El Diablo|10 de Copas": { "<p>next</p>",},
"El Diablo|Sota de Copas": { "<p>next</p>",},
"El Diablo|Caballo de Copas": { "<p>next</p>",},
"El Diablo|Reina de Copas": { "<p>next</p>",},
"El Diablo|Rey de Copas": { "<p>next</p>",},

"La Torre|As de Copas": { "<p>next</p>",},
"La Torre|2 de Copas": { "<p>next</p>",},
"La Torre|3 de Copas": { "<p>next</p>",},
"La Torre|4 de Copas": { "<p>next</p>",},
"La Torre|5 de Copas": { "<p>next</p>",},
"La Torre|6 de Copas": { "<p>next</p>",},
"La Torre|7 de Copas": { "<p>next</p>",},
"La Torre|8 de Copas": { "<p>next</p>",},
"La Torre|9 de Copas": { "<p>next</p>",},
"La Torre|10 de Copas": { "<p>next</p>",},
"La Torre|Sota de Copas": { "<p>next</p>",},
"La Torre|Caballo de Copas": { "<p>next</p>",},
"La Torre|Reina de Copas": { "<p>next</p>",},
"La Torre|Rey de Copas": { "<p>next</p>",},

"La Estrella|As de Copas": { "<p>next</p>",},
"La Estrella|2 de Copas": { "<p>next</p>",},
"La Estrella|3 de Copas": { "<p>next</p>",},
"La Estrella|4 de Copas": { "<p>next</p>",},
"La Estrella|5 de Copas": { "<p>next</p>",},
"La Estrella|6 de Copas": { "<p>next</p>",},
"La Estrella|7 de Copas": { "<p>next</p>",},
"La Estrella|8 de Copas": { "<p>next</p>",},
"La Estrella|9 de Copas": { "<p>next</p>",},
"La Estrella|10 de Copas": { "<p>next</p>",},
"La Estrella|Sota de Copas": { "<p>next</p>",},
"La Estrella|Caballo de Copas": { "<p>next</p>",},
"La Estrella|Reina de Copas": { "<p>next</p>",},
"La Estrella|Rey de Copas": { "<p>next</p>",},

"La Luna|As de Copas": { "<p>next</p>",},
"La Luna|2 de Copas": { "<p>next</p>",},
"La Luna|3 de Copas": { "<p>next</p>",},
"La Luna|4 de Copas": { "<p>next</p>",},
"La Luna|5 de Copas": { "<p>next</p>",},
"La Luna|6 de Copas": { "<p>next</p>",},
"La Luna|7 de Copas": { "<p>next</p>",},
"La Luna|8 de Copas": { "<p>next</p>",},
"La Luna|9 de Copas": { "<p>next</p>",},
"La Luna|10 de Copas": { "<p>next</p>",},
"La Luna|Sota de Copas": { "<p>next</p>",},
"La Luna|Caballo de Copas": { "<p>next</p>",},
"La Luna|Reina de Copas": { "<p>next</p>",},
"La Luna|Rey de Copas": { "<p>next</p>",},

"El Sol|As de Copas": { "<p>next</p>",},
"El Sol|2 de Copas": { "<p>next</p>",},
"El Sol|3 de Copas": { "<p>next</p>",},
"El Sol|4 de Copas": { "<p>next</p>",},
"El Sol|5 de Copas": { "<p>next</p>",},
"El Sol|6 de Copas": { "<p>next</p>",},
"El Sol|7 de Copas": { "<p>next</p>",},
"El Sol|8 de Copas": { "<p>next</p>",},
"El Sol|9 de Copas": { "<p>next</p>",},
"El Sol|10 de Copas": { "<p>next</p>",},
"El Sol|Sota de Copas": { "<p>next</p>",},
"El Sol|Caballo de Copas": { "<p>next</p>",},
"El Sol|Reina de Copas": { "<p>next</p>",},
"El Sol|Rey de Copas": { "<p>next</p>",},

"El Juicio|As de Copas": { "<p>next</p>",},
"El Juicio|2 de Copas": { "<p>next</p>",},
"El Juicio|3 de Copas": { "<p>next</p>",},
"El Juicio|4 de Copas": { "<p>next</p>",},
"El Juicio|5 de Copas": { "<p>next</p>",},
"El Juicio|6 de Copas": { "<p>next</p>",},
"El Juicio|7 de Copas": { "<p>next</p>",},
"El Juicio|8 de Copas": { "<p>next</p>",},
"El Juicio|9 de Copas": { "<p>next</p>",},
"El Juicio|10 de Copas": { "<p>next</p>",},
"El Juicio|Sota de Copas": { "<p>next</p>",},
"El Juicio|Caballo de Copas": { "<p>next</p>",},
"El Juicio|Reina de Copas": { "<p>next</p>",},
"El Juicio|Rey de Copas": { "<p>next</p>",},

"El Mundo|As de Copas": { "<p>next</p>",},
"El Mundo|2 de Copas": { "<p>next</p>",},
"El Mundo|3 de Copas": { "<p>next</p>",},
"El Mundo|4 de Copas": { "<p>next</p>",},
"El Mundo|5 de Copas": { "<p>next</p>",},
"El Mundo|6 de Copas": { "<p>next</p>",},
"El Mundo|7 de Copas": { "<p>next</p>",},
"El Mundo|8 de Copas": { "<p>next</p>",},
"El Mundo|9 de Copas": { "<p>next</p>",},
"El Mundo|10 de Copas": { "<p>next</p>",},
"El Mundo|Sota de Copas": { "<p>next</p>",},
"El Mundo|Caballo de Copas": { "<p>next</p>",},
"El Mundo|Reina de Copas": { "<p>next</p>",},
"El Mundo|Rey de Copas": { "<p>next</p>",},

// ==========================================
// ARCANOS MAYORES X ARCANOS MENORES (ESPADAS) (308)
// ==========================================
"El Loco|As de Espadas": { "<p>next</p>",},
"El Loco|2 de Espadas": { "<p>next</p>",},
"El Loco|3 de Espadas": { "<p>next</p>",},
"El Loco|4 de Espadas": { "<p>next</p>",},
"El Loco|5 de Espadas": { "<p>next</p>",},
"El Loco|6 de Espadas": { "<p>next</p>",},
"El Loco|7 de Espadas": { "<p>next</p>",},
"El Loco|8 de Espadas": { "<p>next</p>",},
"El Loco|9 de Espadas": { "<p>next</p>",},
"El Loco|10 de Espadas": { "<p>next</p>",},
"El Loco|Sota de Espadas": { "<p>next</p>",},
"El Loco|Caballo de Espadas": { "<p>next</p>",},
"El Loco|Reina de Espadas": { "<p>next</p>",},
"El Loco|Rey de Espadas": { "<p>next</p>",},

"El Mago|As de Espadas": { "<p>next</p>",},
"El Mago|2 de Espadas": { "<p>next</p>",},
"El Mago|3 de Espadas": { "<p>next</p>",},
"El Mago|4 de Espadas": { "<p>next</p>",},
"El Mago|5 de Espadas": { "<p>next</p>",},
"El Mago|6 de Espadas": { "<p>next</p>",},
"El Mago|7 de Espadas": { "<p>next</p>",},
"El Mago|8 de Espadas": { "<p>next</p>",},
"El Mago|9 de Espadas": { "<p>next</p>",},
"El Mago|10 de Espadas": { "<p>next</p>",},
"El Mago|Sota de Espadas": { "<p>next</p>",},
"El Mago|Caballo de Espadas": { "<p>next</p>",},
"El Mago|Reina de Espadas": { "<p>next</p>",},
"El Mago|Rey de Espadas": { "<p>next</p>",},

"La Sacerdotisa|As de Espadas": { "<p>next</p>",},
"La Sacerdotisa|2 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|3 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|4 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|5 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|6 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|7 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|8 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|9 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|10 de Espadas": { "<p>next</p>",},
"La Sacerdotisa|Sota de Espadas": { "<p>next</p>",},
"La Sacerdotisa|Caballo de Espadas": { "<p>next</p>",},
"La Sacerdotisa|Reina de Espadas": { "<p>next</p>",},
"La Sacerdotisa|Rey de Espadas": { "<p>next</p>",},

"La Emperatriz|As de Espadas": { "<p>next</p>",},
"La Emperatriz|2 de Espadas": { "<p>next</p>",},
"La Emperatriz|3 de Espadas": { "<p>next</p>",},
"La Emperatriz|4 de Espadas": { "<p>next</p>",},
"La Emperatriz|5 de Espadas": { "<p>next</p>",},
"La Emperatriz|6 de Espadas": { "<p>next</p>",},
"La Emperatriz|7 de Espadas": { "<p>next</p>",},
"La Emperatriz|8 de Espadas": { "<p>next</p>",},
"La Emperatriz|9 de Espadas": { "<p>next</p>",},
"La Emperatriz|10 de Espadas": { "<p>next</p>",},
"La Emperatriz|Sota de Espadas": { "<p>next</p>",},
"La Emperatriz|Caballo de Espadas": { "<p>next</p>",},
"La Emperatriz|Reina de Espadas": { "<p>next</p>",},
"La Emperatriz|Rey de Espadas": { "<p>next</p>",},

"El Emperador|As de Espadas": { "<p>next</p>",},
"El Emperador|2 de Espadas": { "<p>next</p>",},
"El Emperador|3 de Espadas": { "<p>next</p>",},
"El Emperador|4 de Espadas": { "<p>next</p>",},
"El Emperador|5 de Espadas": { "<p>next</p>",},
"El Emperador|6 de Espadas": { "<p>next</p>",},
"El Emperador|7 de Espadas": { "<p>next</p>",},
"El Emperador|8 de Espadas": { "<p>next</p>",},
"El Emperador|9 de Espadas": { "<p>next</p>",},
"El Emperador|10 de Espadas": { "<p>next</p>",},
"El Emperador|Sota de Espadas": { "<p>next</p>",},
"El Emperador|Caballo de Espadas": { "<p>next</p>",},
"El Emperador|Reina de Espadas": { "<p>next</p>",},
"El Emperador|Rey de Espadas": { "<p>next</p>",},

"El Papa|As de Espadas": { "<p>next</p>",},
"El Papa|2 de Espadas": { "<p>next</p>",},
"El Papa|3 de Espadas": { "<p>next</p>",},
"El Papa|4 de Espadas": { "<p>next</p>",},
"El Papa|5 de Espadas": { "<p>next</p>",},
"El Papa|6 de Espadas": { "<p>next</p>",},
"El Papa|7 de Espadas": { "<p>next</p>",},
"El Papa|8 de Espadas": { "<p>next</p>",},
"El Papa|9 de Espadas": { "<p>next</p>",},
"El Papa|10 de Espadas": { "<p>next</p>",},
"El Papa|Sota de Espadas": { "<p>next</p>",},
"El Papa|Caballo de Espadas": { "<p>next</p>",},
"El Papa|Reina de Espadas": { "<p>next</p>",},
"El Papa|Rey de Espadas": { "<p>next</p>",},

"Los Enamorados|As de Espadas": { "<p>next</p>",},
"Los Enamorados|2 de Espadas": { "<p>next</p>",},
"Los Enamorados|3 de Espadas": { "<p>next</p>",},
"Los Enamorados|4 de Espadas": { "<p>next</p>",},
"Los Enamorados|5 de Espadas": { "<p>next</p>",},
"Los Enamorados|6 de Espadas": { "<p>next</p>",},
"Los Enamorados|7 de Espadas": { "<p>next</p>",},
"Los Enamorados|8 de Espadas": { "<p>next</p>",},
"Los Enamorados|9 de Espadas": { "<p>next</p>",},
"Los Enamorados|10 de Espadas": { "<p>next</p>",},
"Los Enamorados|Sota de Espadas": { "<p>next</p>",},
"Los Enamorados|Caballo de Espadas": { "<p>next</p>",},
"Los Enamorados|Reina de Espadas": { "<p>next</p>",},
"Los Enamorados|Rey de Espadas": { "<p>next</p>",},

"El Carro|As de Espadas": { "<p>next</p>",},
"El Carro|2 de Espadas": { "<p>next</p>",},
"El Carro|3 de Espadas": { "<p>next</p>",},
"El Carro|4 de Espadas": { "<p>next</p>",},
"El Carro|5 de Espadas": { "<p>next</p>",},
"El Carro|6 de Espadas": { "<p>next</p>",},
"El Carro|7 de Espadas": { "<p>next</p>",},
"El Carro|8 de Espadas": { "<p>next</p>",},
"El Carro|9 de Espadas": { "<p>next</p>",},
"El Carro|10 de Espadas": { "<p>next</p>",},
"El Carro|Sota de Espadas": { "<p>next</p>",},
"El Carro|Caballo de Espadas": { "<p>next</p>",},
"El Carro|Reina de Espadas": { "<p>next</p>",},
"El Carro|Rey de Espadas": { "<p>next</p>",},

"La Justicia|As de Espadas": { "<p>next</p>",},
"La Justicia|2 de Espadas": { "<p>next</p>",},
"La Justicia|3 de Espadas": { "<p>next</p>",},
"La Justicia|4 de Espadas": { "<p>next</p>",},
"La Justicia|5 de Espadas": { "<p>next</p>",},
"La Justicia|6 de Espadas": { "<p>next</p>",},
"La Justicia|7 de Espadas": { "<p>next</p>",},
"La Justicia|8 de Espadas": { "<p>next</p>",},
"La Justicia|9 de Espadas": { "<p>next</p>",},
"La Justicia|10 de Espadas": { "<p>next</p>",},
"La Justicia|Sota de Espadas": { "<p>next</p>",},
"La Justicia|Caballo de Espadas": { "<p>next</p>",},
"La Justicia|Reina de Espadas": { "<p>next</p>",},
"La Justicia|Rey de Espadas": { "<p>next</p>",},

"El Ermitaño|As de Espadas": { "<p>next</p>",},
"El Ermitaño|2 de Espadas": { "<p>next</p>",},
"El Ermitaño|3 de Espadas": { "<p>next</p>",},
"El Ermitaño|4 de Espadas": { "<p>next</p>",},
"El Ermitaño|5 de Espadas": { "<p>next</p>",},
"El Ermitaño|6 de Espadas": { "<p>next</p>",},
"El Ermitaño|7 de Espadas": { "<p>next</p>",},
"El Ermitaño|8 de Espadas": { "<p>next</p>",},
"El Ermitaño|9 de Espadas": { "<p>next</p>",},
"El Ermitaño|10 de Espadas": { "<p>next</p>",},
"El Ermitaño|Sota de Espadas": { "<p>next</p>",},
"El Ermitaño|Caballo de Espadas": { "<p>next</p>",},
"El Ermitaño|Reina de Espadas": { "<p>next</p>",},
"El Ermitaño|Rey de Espadas": { "<p>next</p>",},

"La Rueda de la Fortuna|As de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|2 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|3 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|4 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|5 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|6 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|7 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|8 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|9 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|10 de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|Sota de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|Caballo de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|Reina de Espadas": { "<p>next</p>",},
"La Rueda de la Fortuna|Rey de Espadas": { "<p>next</p>",},

"La Fuerza|As de Espadas": { "<p>next</p>",},
"La Fuerza|2 de Espadas": { "<p>next</p>",},
"La Fuerza|3 de Espadas": { "<p>next</p>",},
"La Fuerza|4 de Espadas": { "<p>next</p>",},
"La Fuerza|5 de Espadas": { "<p>next</p>",},
"La Fuerza|6 de Espadas": { "<p>next</p>",},
"La Fuerza|7 de Espadas": { "<p>next</p>",},
"La Fuerza|8 de Espadas": { "<p>next</p>",},
"La Fuerza|9 de Espadas": { "<p>next</p>",},
"La Fuerza|10 de Espadas": { "<p>next</p>",},
"La Fuerza|Sota de Espadas": { "<p>next</p>",},
"La Fuerza|Caballo de Espadas": { "<p>next</p>",},
"La Fuerza|Reina de Espadas": { "<p>next</p>",},
"La Fuerza|Rey de Espadas": { "<p>next</p>",},

"El Colgado|As de Espadas": { "<p>next</p>",},
"El Colgado|2 de Espadas": { "<p>next</p>",},
"El Colgado|3 de Espadas": { "<p>next</p>",},
"El Colgado|4 de Espadas": { "<p>next</p>",},
"El Colgado|5 de Espadas": { "<p>next</p>",},
"El Colgado|6 de Espadas": { "<p>next</p>",},
"El Colgado|7 de Espadas": { "<p>next</p>",},
"El Colgado|8 de Espadas": { "<p>next</p>",},
"El Colgado|9 de Espadas": { "<p>next</p>",},
"El Colgado|10 de Espadas": { "<p>next</p>",},
"El Colgado|Sota de Espadas": { "<p>next</p>",},
"El Colgado|Caballo de Espadas": { "<p>next</p>",},
"El Colgado|Reina de Espadas": { "<p>next</p>",},
"El Colgado|Rey de Espadas": { "<p>next</p>",}

};

// Función para buscar en la base local (fallback offline)
window.buscarDuplaLocal = function(cartaA, cartaB) {
    const key1 = cartaA + "|" + cartaB;
    const key2 = cartaB + "|" + cartaA; // orden inverso por si acaso

    if (window.baseDeDatosDuplas[key1]) {
        return { encontrada: true, ...window.baseDeDatosDuplas[key1], orden: 'directo' };
    }
    if (window.baseDeDatosDuplas[key2]) {
        return { encontrada: true, ...window.baseDeDatosDuplas[key2], orden: 'inverso' };
    }
    return { encontrada: false, mensaje: 'Dupla no encontrada en base local.' };
};

// Función para agregar duplas locales (útil para testear)
window.agregarDuplaLocal = function(cartaA, cartaB, significado, keywords) {
    const key = cartaA + "|" + cartaB;
    window.baseDeDatosDuplas[key] = { significado, keywords: keywords || [] };
};
